Initial Cucumber Scenario for Client
shweta-kumaran/CastNXTfall24 pull request #112
Opened 2024-11-20 21:25 UTC by shahharsh06

2024-11-20 21:36 UTC, shweta-kumaran reviewed
Looks good to me, I am unable to check if it passes if @rahulb99 can verify?

2024-11-21 17:14 UTC, rahulb99 requested changes

2024-11-21 17:14 UTC, rahulb99 commented on spec/features/ClientHomepage.feature
> +    Then the client should see a list of projects
what is `projects` here?

2024-11-21 17:14 UTC, rahulb99 commented on spec/features/step_definitions/ client_homepage.steps.js
> +        then('the client should see a list of projects', async () => {
same here

2024-11-21 17:16 UTC, rahulb99 commented
Also, merge the `main` branch and update README instructions to create a client with email and password, as mentioned in your feature file

2024-11-21 18:48 UTC, shahharsh06 commented on spec/features/ClientHomepage.feature
> +    Then the client should see a list of projects
Correct in recent push. Please have a look at it.

2024-11-21 18:49 UTC, shahharsh06 commented on spec/features/step_definitions/ client_homepage.steps.js
> +        then('the client should see a list of projects', async () => {
Correct in recent push. Please have a look at it.

2024-11-22 16:23 UTC, shweta-kumaran approved these changes

2024-11-22 19:03 UTC, rahulb99 approved these changes
LGTM

2024-11-22 19:08 UTC, merged